bridgecrewio/checkov-vscode

src/extension.ts, src/userInterface.ts, src/utils.ts
**In This PR**
- Fix - run as-you-code scans only on terraform files (Needed to exclude log file changes )
=> Fix(as-you-code): watch tf files only

docs/pull_request_template.md, src/checkovRunner.ts, src/extension.ts, src/userInterface.ts, src/utils.ts
**In This PR**
- Add support to `json`, `yaml`, and `yml` files.
- Handle empty file checkov response.
- Fix PR template file.
**Related links**
- https://bridgecrew.atlassian.net/browse/BC-3950
=> fix(json,yml): support json+  yml, and empty file

README.md, package.json, src/checkovInstaller.ts
**In This PR**
- Remove `Brew` as a checkov installment medium.
- Add `python` as a dependency in the `README`.
- Enable lower versions of vscode to install the extension.
=> Fix(brew): remove install with brew, add pip 3 dep

src/checkovRunner.ts
**In This PR**
- docker parameter to remove the docker container after check on the runner.
This will prevent to create hundreds of containers, as the Checkov creates a new container for every run.
Without that change, the user machine will looks like this:
```shell
> docker container ls -a
CONTAINER ID   IMAGE                COMMAND                  CREATED              STATUS                          PORTS     NAMES
286efb66ee54   bridgecrew/checkov   "checkov -s --skip-c…"   About a minute ago   Exited (0) 56 seconds ago                 suspicious_antonelli
befd916ce9d1   bridgecrew/checkov   "checkov -s --skip-c…"   About a minute ago   Exited (0) About a minute ago             funny_bartik
9fb956a9fa0f   bridgecrew/checkov   "checkov -s --skip-c…"   About a minute ago   Exited (0) …
```
=> include param to remove container on the runner

package.json, src/checkovRunner.ts, src/configuration.ts, src/extension.ts
- Add `Certificate` to the settings
- If set, pass the cert to checkov using the `-ca` argument
=> feat(CA-Cert): enable user to set custom ca cert and pass it to checkov

src/checkovRunner.ts
- Add missing docker image name needed to invoke checkov run via docker
- Error was raised by a user in slack (https://codifiedsecurity.slack.com/archives/C01KPD735D3/p1624391600009200)
=> fix(docker run): add missing docker image name

src/checkovInstaller.ts
- Fix checkov scanning via pipenv resulting in 422
* pipenv is keeping semver versioning, meaning it will not update the version to a higher major (major.minor.patch)
So since we updaed to version 2 of checkov it didn’t update and ran on checkov 1.0.821
Recently we changed the bridgecrew api schema validation and the endpoint didn’t get something that was marked as required, resulting in 422 error Validation Failed
=> fix(pipenv checkov): use most recent version

src/checkovRunner.ts
- Fixes parsing when the result has multiple frameworks (IaC + Secrets)
- Also removes the temporary hardcoded framework filter
=> handle results with multiple frameworks

package-lock.json, package.json, src/checkovInstaller.ts, src/checkovRunner.ts, src/commands.ts, src/configuration.ts, src/extension.ts, src/suggestFix.ts, src/userInterface.ts, src/utils.ts
- Adds "checkov version" setting, allowing users to specify a specific version to use (>= 2.0.0) or 'latest' (default)
- Adds an "about checkov" command to view the checkov installation details
- Adds a command to open the checkov log
(Edited)
=> Pin checkov version

src/checkovInstaller.ts, src/checkovRunner.ts, src/extension.ts, src/utils.ts
- Updates each runner method (docker, pip, pipenv) to run from the workspace root and pass the relative file path to the runner
- runs `git remote -v` and tries to parse the output to determine the repo ID (this allows VSCode to honor platform suppressions)
Collectively, these two changes allow VSCode to match suppressions defined in the platform.
=> pull the repo name from git if it exists

src/checkovInstaller.ts, src/checkovRunner.ts, src/utils.ts
- Fixes an issue introduced by https://github.com/bridgecrewio/checkov-vscode/pull/60 where the docker file argument was not properly converted to a windows path
- Fixes pipenv and pip installation methods on Windows, which did not seem to work with a --user installation
=> fix windows path and installation method issues

src/utils.ts
- This is a temporary workaround to correctly set the `--repo-id` parameter in the case where the git server is not hosted at the root level (e.g., `https://company.example.com/git`). This would result in the repo ID being passed as `git/owner/repo`, which is both incorrect from the repo standpoint, and also (currently) not supported in [Checkov](https://github.com/bridgecrewio/checkov/issues/1559).
There will need to be a future workaround to handle these types of URLs as well as repo names with multiple slashes in them, which is a feature supported by Gitlab.
=> Temp repo id fix

src/checkovRunner.ts, src/utils.ts
- When running on windows without docker installed and having checkov installed via PIP if you had a space in the file path name e.g. C:\temp\demo project\template.yaml then the scan would fail due to the space. Changes made are to wrap the -f arguments with quotes to ensure the full path is taken into account.
Fixes #63
=> fix: wrap -f with quotes

src/checkovRunner.ts
- Handle error thrown after file scanned with no errors and resources
```
[debug]: Response from version command: 2.0.528
[debug]: Checkov scan process exited with code 0 
[debug]: Checkov task output: {"stdout":"{\n    \"passed\": 0,\n    \"failed\": 0,\n    \"skipped\": 0,\n    \"parsing_errors\": 0,\n    \"resource_count\": 0,\n    \"checkov_version\": \"2.0.528\"\n}\n"}
[error]: Failed to get response from Checkov. {"error":{"message":"Cannot read property 'failed_checks' of undefined","stack":"TypeError: Cannot read property 'failed_checks' of undefined\n\tat parseCheckovResponse (/Users/steve/.vscode/extensions/bridgecrew.checkov-1.0.51/out/checkovRunner.js:113:44)\n\tat ChildProcess.<anonymous> (/Users/steve/.vscode/extensions/bridgecrew.checkov-1.0.51/out/checkovRunner.js:93:29)\n\ …
```
=> Fix(no resources scan): handle 0 scanned resources checkov response

src/utils.ts
- Fixes the logic to create "diagnostic" objects. It was not correctly looking up custom policies because of the way we display custom policy docs. The result was that any resource with custom policy violations had no quick fix actions available.
The cause was [here](https://github.com/bridgecrewio/checkov-vscode/blob/f4c9e078a876befa708291ae043c39a0ea18f8f9/src/diagnostics.ts#L20). 
`diagnostic.code` is a string for custom policies, so `diagnostic.code.value` returns undefined, which breaks the map lookup [here](https://github.com/bridgecrewio/checkov-vscode/blob/f4c9e078a876befa708291ae043c39a0ea18f8f9/src/suggestFix.ts#L12).
=> fix diagnostic creation for custom policies

src/suggestFix.ts
- We are planing to integrate a skip mechanism for k8s resources, until then we will block the comment generation for k8s as it breaks the YAML format
=> Chore(k8s skip): disable k8s skip comment generation

src/checkovInstaller.ts, src/checkovRunner.ts, src/configuration.ts, src/extension.ts
- Fixes the new python version check, which used "python" (not "python3") and crashed for most users
- Also runs it during installation, so that it doesn't run during VSCode startup, and so it doesn't run if you are using docker
=> use python3 in version command and run during installation

src/checkovInstaller.ts
- If all install / update options fail, use the `checkov` executable, if available. This makes it easier for customers who need to manually install checkov to get around VPNs, etc to install some other way and then have VSCode pick it up.
=> use a global checkov executable if available and all other installation options fail

src/checkovRunner.ts, src/utils.ts
- Updates the repo URL parsing to validate that the repo name will actually be accepted by checkov
- Removes the default repo name, allowing users to specify one from a config file as a fallback to when `git remote -v` parsing fails
Example `git remote -v` output:
```
origin  codecommit::us-west-2://repo_name (fetch)
origin  codecommit::us-west-2://repo_name (push)
```
This would get parsed to `/repo_name` and passed as the repo-id to checkov, which would then fail. Since there is no good "org" value to use, the best option is to just pass nothing for the repo-id and allow the user to specify the value in a config file if they want. Otherwise, it will just use the checkov default (and it's all arbitrary at this point anyways).
=> validate repo URL parsing and fall back to config file

src/utils.ts
- Fixes an issue parsing the `git remote` output if the remote URL ends with a slash (e.g., `git@github.com:bridgecrewio/checkov-vscode.git/`)
=> handle git remote URLs with trailing slash

src/checkov/checkovParser.ts, src/checkov/models.ts, src/diagnostics.ts
- Adds severities in the output in front of the check name, if the severity exists (e.g., `MEDIUM: Ensure...`)
=> show severity in output if it exists

package.json, src/checkov/models.ts, src/commands.ts, src/extension.ts, src/utils.ts
- Adds a file hash-based caching mechanism so skip rescanning files that have not changed since the last scan. By caching purely based on the hash (as opposed to the filename), it also gracefully handle scans that occur on temp (unsaved) files.
=> Don't rescan files that have not changed

src/checkov/models.ts, src/utils.ts
- Fixes #80 when loading a saved cache after restarting VSCode. The saved object doesn't get deserialized into a BoundedFileCache, so the class methods do not work. This replaces those methods with helper methods and a new interface type. It preserves compatibility with a saved cache.
=> use plain JS objects for cache

package-lock.json, package.json, src/checkov/checkovRunner.ts
When running on M1 processors (maybe on more archs), some checkov containers are not killed when `onCancellationRequested` event is fired. the reason is some percentage of them are throwing the following error: 
`qemu: uncaught target signal 6 (Aborted) - core dumped`. This is due to this bug - https://github.com/docker/for-mac/issues/6264
Now that we started scanning all file types this has become a big issue, because docker processes grew significantly.
In this PR I replaced the `child_proccess.kill` method with `docerode` kill method which works much better. I also attach a unique identifier for each run to be passed to the `kill` command.
In addition, removing the `runVersionCommand` on each run, which setup a container from scratch on each run for no reason, overloading the docker …
=> using dockerode to kill containers

README.md
Change badge from svg to png due to following error in publish: `SVGs are restricted in README.md; please use other file image formats, such as PNG: https://vsmarketplacebadges.dev/installs-short/Bridgecrew.checkov.svg`
=> change badge to png

src/utils.ts
- Entring a log file (checkov.log for example) triggered a lot of scans that where canceled and recreated on writing.
This PR Add `.log` files to the unsupported ext to prevent that.
=> skip scanning of log files

package-lock.json, package.json, src/checkov/checkovRunner.ts, src/configuration.ts, src/extension.ts
- Added setting "Skip Frameworks" to take a space separated list of frameworks to skip during scanning
- This results in the `checkov` cli command being appended with `--skip-framework <list of frameworks>` 
- Added setting "Framworks" to take a space separated list of frameworks to use during scanning
- This results in the `checkov` cli command being appended with `--framework <list of frameworks>` 
```bash
[info]: Starting to scan. 
[debug]: Output: 
[info]: repo urlgit@github.com:mapbox/security-breakglass.git 
[info]: repo namemapbox/security-breakglass 
[info]: Running checkov: 
[info]: checkov --output-bc-ids -s --bc-api-key **** --repo-id mapbox/security-breakglass -f "/Users/billybryant/github/mapbox/security-breakglass/.github/workflows/bandit.yml" --skip-check BC_LIC* -o json …
```
=> Adding Framework/Skip-Framework functionality

src/checkov/checkovRunner.ts
Add default repo-id
https://github.com/bridgecrewio/checkov-vscode/issues/136
=> Add default repo-id

README.md
=> Remove BC from README

README.md, package.json, src/configuration.ts, src/userInterface.ts
=> Remove BC references
