- src/checkovRunner.ts
- src/extension.ts
- src/utils.ts
**In This PR**
- Add the source and version environment variables to checkov's run
> Fix(Checkov): Pass Variables to Checkov

- README.md
**In This PR**
- Remove irrelevant badges from `README`
> Chore(README): remove readme badges

- .github/workflows/build.yml
**In This PR**
- Change CI `build` workflow to work on a push to master
> Fix(CI): trigger build on master push

- .github/workflows/build.yml
- .github/workflows/publish.yml
**In This PR**
- Use access token in CI workflows.
> Fix(CI): use access token

- package.json
- src/checkovInstaller.ts
- src/checkovRunner.ts
- src/extension.ts
- src/token.ts
- src/utils.ts
**In This PR**
- Fix brew install.
- Enable user to use system checkov instead.
- Improve logs.
**Pictures/videos**
- Configuration screen:
> Fix(Checkov): Enable system checkov 

- src/checkovInstaller.ts
- src/checkovRunner.ts
- src/extension.ts
- src/utils.ts
**In This PR**
- Use `pip3` without specifying a target
> Use pip3 to install checkov without target

- README.md
readme-beta-announcement
- adds information about the nature of this current release - terms, restrictions, etc.
**In This PR**
- 
**Pictures/videos**
> readme-beta-announcement

- README.md
- package.json
**In This PR**
- Update to the information in the plugin configuration page within VSCode
- Update to the disclaimer section of the readme.
- [ * ] I've reviewed my own code
> [skip-ci] Add more detail to API usage docs

- README.md
**In This PR**
- Fixed Integrations link, as it defaults to a "Oops! Something went wrong." page when linking to the root /integrations.
**Pictures/videos**
- [ NA] I've reviewed my own code
> Fixed integrations link

- src/checkovInstaller.ts
- src/checkovRunner.ts
- src/extension.ts
- src/utils.ts
**In This PR**
- Try to install Checkov with docker/pip3/pipenv
- Checkov runner integrate with a suitable Checkov executable
> Install Checkov with docker/pip3/pipenv

- src/checkovRunner.ts
**In This PR**
- Docker run checkov with log level debug
> Docker run checkov with log level debug

- src/checkovRunner.ts
**In This PR**
- Add quotes around docker volume
> Add quotes around docker volume

- src/checkovRunner.ts
**In This PR**
- Add start JSON char `[`
> Add start JSON char "["

- src/checkovRunner.ts
- src/utils.ts
**In This PR**
- Convert Windows path to Unix path in Docker
> Convert Windows path to Unix path in Docker

- src/checkovRunner.ts
**In This PR**
- Add more logs
> Add more logs

- src/extension.ts
- src/userInterface.ts
**In This PR**
- Add indication texts for update Checkov and Checkov scan states
- Trigger file scan right after Checkov update
> Improve UX

- src/extension.ts
**In This PR**
- Disable running after initialization on unsupported format files.
> Fix(initial scan): avoid unwanted noise

- src/utils.ts
- Change the max buffer to support pip installation of Checkov
> Change the max buffer to support pip installation of Checkov

- package-lock.json
- package.json
- src/checkovRunner.ts
- src/extension.ts
- src/parseCheckovConfig.ts
- src/utils.ts
- Add support for checkov configuration using .checkov.yml / .checkov.yaml file placed the root of workspace. 
- Remove default skip check for CKV_AWS_52. (Checkov PR: https://github.com/bridgecrewio/checkov/pull/1303)
- If configuration file is not present, scanning will proceed as usual.
> Use config file

- .github/workflows/build.yml
- .github/workflows/pr-test.yml
- .github/workflows/publish.yml
> Support white list

- src/checkovRunner.ts
- Skips the secrets framework as a temporary hotfix to failed parsing issues
> skip secrets scans

- package-lock.json
- package.json
- src/checkovRunner.ts
- src/configuration.ts
- src/extension.ts
- Adds an option to show BC_ IDs in the scan results (and also in the skip comments)
> add option to use BC platform IDs

- README.md
- package.json
- src/configuration.ts
- src/extension.ts
- src/userInterface.ts
- Requested by users - error message caused unwanted noise.
- Reduce the content of the error message.
- Allow users to disable the error message entirely.
> Feat(Error message): reduce noise by minimizing content and allow users to disable

- src/checkovInstaller.ts
- src/checkovRunner.ts
- src/utils.ts
- fixes an issue getting the pip3 executable on *nix
- fixes an issue with spaces in the ca-cert path
> Path fixes

- package.json
- src/checkovRunner.ts
- src/configuration.ts
- src/extension.ts
- src/utils.ts
> added support for prisma token

- src/checkovRunner.ts
- Fix checkov response with multiple error types
https://github.com/bridgecrewio/checkov-vscode/issues/77
> fix(scan): handle array response from checkov

- package.json
- src/checkovRunner.ts
- src/configuration.ts
- src/extension.ts
- Passes PRISMA_API_URL to docker
- Adds a checkov debug log option
> pass prisma API URL to docker

- package.json
- Fixes the example prisma API url
> fix example prisma URL

- src/checkovRunner.ts
- src/parseCheckovConfig.ts
- src/utils.ts
- Properly mounts the ca cert argument into the docker container
- Refactors file mounting and arguments a little bit for docker
> mount CA cert in docker and refactor docker params

- src/checkovRunner.ts
- Pretty prints the checkov JSON stdout if it is valid
> pretty print json output if possible

- src/checkov/checkovRunner.ts
- Remove `SCA` flag sent to `Checkov` to improve scan time
> Fix(SCA): temporary disable to reduce scan time until Checkov fix

- README.md
- updates instructions for getting to the extension logs
> update instructions for getting logs

- src/extension.ts
- src/utils.ts
- Support `.bicep` file scanning
> feature(bicep support): support bicep file scanning

- package.json
- src/checkov/checkovRunner.ts
- src/configuration.ts
- src/extension.ts
- Added option to configure external checks directory
> External checks dir config

- package-lock.json
- package.json
> chore(dependencies): update npm dependencies after audit

- src/checkov/checkovRunner.ts
- Skip license checks to avoid broken messages
> chore(checkov scan): skip license checks

- package-lock.json
- package.json
- src/configuration.ts
- src/extension.ts
- src/utils.ts
- tsconfig.json
- Accepts the value `platform` for the version, in which case it will use the platform API to get the checkov version during installation.
> Allow using the same version as the platform

- README.md
Update the install badge according to new standards
> update svg in readme

- package-lock.json
- package.json
- src/checkov/checkovRunner.ts
- src/configuration.ts
- src/extension.ts
- Adds a setting for the new --no-cert-verify option in checkov
> add option for no cert verify

- src/extension.ts
- Disable background scan on changes without save
> remove new line scan on temp file
